name: Construction d'un projet

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  create-folder:
    name: Create-folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create folder on remote VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASWORD }}
          port: ${{ secrets.PORT }}
          script: whoami

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Construction de l'application avec Maven
        run: mvn -B package -DskipTests=true --file pom.xml